### ISSUE TITLE
[Inputs] Export non-InputContainer-wrapped input components

### ISSUE THREAD

**Issue by eric-martinez-sociomantic** [sociomantic-tsunami/nessie-ui#16]
### Currently 

Most input-type components are only exported wrapped in InputContainer:

 - CheckboxTextInput
  - CodeEditor
  - Datepicker
  - DimensionsInput
  - FlounderDropdown
  - PasswordInput
  - TagInput
  - TextArea
  - TextInputWithDropdown
 -  ValuedTextInput

The only exception is the InputField and TextInput components, the later being the former wrapped in an InputContainer.

### Problem

This hinders component composability.

### Wanted

For each input type, export a simple input without InputContainer.

**Comment by eric-martinez-sociomantic** [comment]
One possibility here is to re-implement the InputContainer component as a `withLabel` higher-order component, so you could do stuff like:
```
const DimensionsInputWithLabel = withLabel( DimensionsInput );
```

(Where DimensionsInput above is _just the input_, without a built-in label, etc.)

**Comment by conor-cafferkey-sociomantic** [comment]
Unblocking this. I have already made a start here as part of #38

**Comment by conor-cafferkey-sociomantic** [comment]
`withInputContainer` higher-order component has been [implemented](https://github.com/sociomantic-tsunami/nessie/commit/018d3bb5dcc4671e358718b0f4244109c8fcc5ef#diff-da322c968311684aa8f9d21fca668f36). This will ease the transition for implementations already using the pre-composed inputs-with-containers. (InputContainer and this HOC will eventually be removed in a future release.)

This issue should remain open until:
- [ ] `<InputContainer>` is removed from all input components
- [ ] all test drivers and tests are updated accordingly
