### ISSUE TITLE
[UploadButton] Implement component

### ISSUE THREAD

**Issue by eric-martinez-sociomantic** [sociomantic-tsunami/nessie-ui#17]
To enable the Uploader to work in IE10 we need to replace the Upload `<button>` with a `<label>` styled as a button.

> - Use the accessibility for attribute on a label, pointing to the input
> - Make sure the input is not hidden
> - Hide the input by moving it off screen using absolute positioning

**Comment by eric-martinez-sociomantic** [comment]
This button:
```
<Button role = { buttonRole }
        className  = { uploaderButtonClass }
        onClick    = { !isDisabled && onClick }
        isDisabled = { isDisabled }
        isReadOnly = { isReadOnly }
        iconType   = { iconType }>
    { buttonLabel }
</Button>
```

should be replaced with a `<label>` styled to look like a button when `uploadState="default"`. For `uploadState="uploaded"` the button is kept.

**Comment by eric-martinez-sociomantic** [comment]
There is a misalignment with the shadow and the content.
![screen shot 2017-10-16 at 15 56 46](https://user-images.githubusercontent.com/17337153/31620411-7a420d4e-b297-11e7-897e-227de7079396.png)

**Comment by eric-martinez-sociomantic** [comment]
Also the shadow in the "uploading" and "uploaded" uploading states is not aligned as well.
![screen shot 2017-10-16 at 12 56 12](https://user-images.githubusercontent.com/17337153/31620553-d4dbc8f8-b297-11e7-87a5-a4efefc839aa.png)

**Comment by eric-martinez-sociomantic** [comment]
- [ ] Tested in IE10.

**Comment by conor-cafferkey-sociomantic** [comment]
The current Uploader component makes no sense. Let’s deprecate it and implement a new UploadButton component consisting of __just the button__ (to be implemented as a styled `<label>` as described above).

**Comment by conor-cafferkey-sociomantic** [comment]
This issue is no longer valid – you can just build uploader will be built from existing components (e.g: Button, ProgressBar, etc.)
