### ISSUE TITLE
[Inputs] Don’t expose DOM refs

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie-ui#266]
### Currently

Most of our input-type components provide an `inputRef` prop where a ref callback receives a reference to the relevant DOM-level `<input>` inside the component. 

The primary reason for this is so that consumer code can call `ref.focus()`. 

### Problem

The interface that our components provide should be defined _strictly_ in terms of components and _never_ in terms of DOM elements (see also https://github.com/sociomantic-tsunami/nessie/issues/248, https://github.com/sociomantic-tsunami/nessie/issues/260).

Passing references to DOM elements is incompatible with this philosophy since it exposes the internal implementation of the components. What’s worse, this approach actually demands that the consumer has some level of knowledge of the internals of the component.

### Wanted

All callback props (events, refs, etc.) should provide abstractions strictly in terms of components and never in terms of their constituent DOM elements.

Instead of exposing the `<input>` via callback ref, expose a `focus()` function instead.

**Comment by daniel-martic-sociomantic** [comment]
Opened [issue in LochNess](https://github.com/sociomantic-tsunami/lochness/issues/22) so that we can use `React.createRef()`
