### ISSUE TITLE
[All components] Improve test drivers

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie-ui#267]
### Currently

Nessie provides a suite of [test drivers](https://github.com/sociomantic-tsunami/nessie/blob/master/src/Testing/ComponentDriver/README.md) to allow consumers to use Enzyme to write tests without knowing the internal structure/implementation of the components.

There are three use cases for the currently implemented test drivers:

 1. Simulating user-triggered events on the correct element within the component (e.g. `click()`)
 1. Returning references to props with `PropType.node` _as they occur in the tree rendered by the component_ (e.g. `getContent()`)
 1. Returning values from the DOM (in the case of uncontrolled inputs) (e.g. `getValue()`)

Test drivers extend from a set of pre-defined [common drivers](https://github.com/sociomantic-tsunami/nessie/tree/master/src/Testing/CommonDrivers).

### Problem

- The implementation of the test drivers is inconsistent
- Exactly _what_ the test drivers should do and _how_ they do it is not well defined
- The [common drivers](https://github.com/sociomantic-tsunami/nessie/tree/master/src/Testing/CommonDrivers) assume that a there is only one element of interest inside the component (e.g. a single `<input>`) and assume that all events should be simulated on that element.  This rarely makes sense, even for quite simple components. 

#### Purpose (_what_)

To allow consumers to use Enzyme to write **integration tests simulating user interactions with the Nessie components** without the knowing the internal structure/implementation of the components.

#### Implementation (_how_)

For each component:
- for each event callback prop `onEvent`, a corresponding `event()` driver function must exist
- each `event()` driver function must locate the appropriate _element_ within the component and call Enzyme's `simulate( 'event' )` on that element
- for any `onChange` callback props:
  - the corresponding `change` driver function should accept an argument with the new (changed) value. That is, `change( value )`
  - before calling `simulate( 'change' )` on the appropriate element,  the  `change( value )` driver function should first change the `value` attribute of the element. That is, `element.value = value`
- where the component contains child components on which the consumer may want to simulate events, getter methods should be provided. For example a SliderGroup might have `getSlider( index )` the returns a ReactWrapper with the Slider component at `index`.

The common drivers should be either be re-implemented or removed.

**Any functionality beyond the above should no longer be included**

#### Examples

If we have a callback prop `onClick` we must have a corresponding `click()` driver function that:
 1. locates the appropriate element within the component that should receive the click:  `element = wrapper.find( ... )`
 1. calls `simulate( 'click' )` on the Enzyme wrapper corresponding to the element: `element.simulate( 'click' )`

If we have a callback prop `onFocus` we must have a corresponding `focus()` driver function that:
 1. locates the appropriate element within the component that should receive focus:  `element = wrapper.find( ... )`
 1. calls `simulate( 'focus' )` on the Enzyme wrapper corresponding to the element: `element.simulate( 'focus' )`

If we have a callback prop `onChange` we must have a corresponding `change( value )` driver function that:
 1. locates the appropriate element within the component that should change:  `element = wrapper.find( ... )`
 1. sets the `value` attribute of element: `element.getNode().value = value`
 1. calls `simulate( 'change' )` on the Enzyme wrapper corresponding to the element: `element.simulate( 'change' )`

**Comment by conor-cafferkey-sociomantic** [comment]
Updated the requirements above. This issue most likely deserves its own Milestone.

**Comment by daniel-martic-sociomantic** [comment]
merged
