### ISSUE TITLE
[Uploader] label proptype is set to string, should be PropTypes.node

### ISSUE THREAD

**Issue by john-hannagan-sociomantic** [sociomantic-tsunami/nessie-ui#428]
### Currently

The label proptype for uploader is set to `string`, which causes warnings when passing totally-legit react components as labels. 

### Wanted
Should be `PropTypes.node` for string or components innit?

**Comment by conor-cafferkey-sociomantic** [comment]
> Should be PropTypes.node for string or components innit?

Correct and right
