### ISSUE TITLE
Table throwing 'cannot find className of undefined'

### ISSUE THREAD

**Issue by joshuef** [sociomantic-tsunami/nessie-ui#483]
Right now we've using `TableCell` and for some reason it's throwing ` Cannot read property 'className' of undefined` here:
https://github.com/joshuef/peruse/blob/WebId-MasterMerge/app/components/UrlList/UrlList.jsx#L67

(using 6.1.1.).

I've tried adding a class in our code incase that was just missing, but that still doesn't solve it.

It's not clear to be what's throwing though as we're using the npm released code.

**Comment by joshuef** [comment]
Actually seems like this is due to our code returning _nothing_ here all of a sudden. 

Nessie is fine. Nothing to see here!

**Comment by joshuef** [comment]
Scratch that, it's the `Table` throwing here. Same code all works if `Table` is replaced with `div`

**Comment by joshuef** [comment]
Ah, i'd forgotten this. I'll test it out and see if that's what's up.

**Comment by joshuef** [comment]
That was indeed the issue. Thanks @conor-cafferkey-sociomantic !!!!! 💥

**Comment by joshuef** [comment]
(Nice to have suggestion: Table/Things should throw a relevant error if the children aren't as expected)

**Comment by conor-cafferkey-sociomantic** [comment]
Glad to help! Yes good idea, I’ve opened an issue: ****
