### ISSUE TITLE
[Build] Export a dev bundle

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie-ui#506]
### Currently

In the `dist` folder we have a ~dist bundle (`index.js`) and a dev bundle (the poorly-named `displayComponents.js`)~ commonjs dist bundle and a global/window dist bundle.

### Problem

~`displayComponents.js` is a confusing name.~ There is no dev bundle.

### Wanted

- [x] ~Deprecate the `displayComponents.js` bundle and~ create a new `index.dev.js` bundle

**Comment by mahmoud-zakria-sociomantic** [comment]
@conor-cafferkey-sociomantic This one we can say now it's already implemented or needs any modification yet?
