### ISSUE TITLE
[Text] Line height prop

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie-ui#539]
A line height prop to let you configure Text component’s the line height

**Comment by mahmoud-zakria-sociomantic** [comment]
@conor-cafferkey-sociomantic what must be the default value `normal` or `undefined`?

**Comment by mahmoud-zakria-sociomantic** [comment]
@damian-rodriguez-sociomantic  @conor-cafferkey-sociomantic 
How about making it with `propTypes.oneOf`? and we add on the list the `normal` keyword? just in case we wanted to choose/revert back to the default value which is `normal`

**Comment by conor-cafferkey-sociomantic** [comment]
My description above was a bit confusing. I should have wrote:

The prop should accept any CSS line height string and **not** keyword-based line heights (`S`, `M`, `L`, etc.).
