### ISSUE TITLE
[Table] Should not have divider after last TableRow

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie-ui#545]
### Currently 
![screen shot 2018-08-21 at 18 39 48](https://user-images.githubusercontent.com/13482427/44415821-a4d35180-a571-11e8-9640-0cf2bccc68f5.png)

### Wanted

- [x] The last divider line above ☝️ should not exist.
- [x] There _should be_ a divider between the header row and the table body

**Comment by daniel-martic-sociomantic** [comment]
Also fixed issues with `borders: columnDivider`:

<img width="404" alt="screen shot 2018-08-24 at 11 02 12" src="https://user-images.githubusercontent.com/36076598/44575856-61edc580-a78d-11e8-9c91-925ef67999f7.png">

and `borders: cell` (double border between cells):

<img width="491" alt="screen shot 2018-08-24 at 11 02 22" src="https://user-images.githubusercontent.com/36076598/44575861-66b27980-a78d-11e8-8b1d-dc4a44f23854.png">
