### ISSUE TITLE
[Tooltip] z-index

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie-ui#566]
### Problem

`.tooltip` previously had `z-index: 10000`, now it has none.

### Wanted

Restore previous `z-index`

**Comment by mahmoud-zakria-sociomantic** [comment]
Strange! last time I gave it a `z-index: 9999` and previously there wasn't z-index for it.

<img width="517" alt="screen shot 2018-08-30 at 10 45 35" src="https://user-images.githubusercontent.com/37908294/44840675-ddde8680-ac41-11e8-93b5-8e5e22b2c676.png">
