### ISSUE TITLE
[Paginator] First and last page don't have same font/styles

### ISSUE THREAD

**Issue by daniel-martic-sociomantic** [sociomantic-tsunami/nessie-ui#654]
## Current

The first and the last page buttons aren't consistent with other styles

<img width="225" alt="paginator" src="https://user-images.githubusercontent.com/36076598/46680377-3f065c00-cbe9-11e8-8ea5-396832a0ec66.png">

## Wanted

All buttons should have same fonts and have consistent styles

**Comment by mahmoud-zakria-sociomantic** [comment]
#
