### ISSUE TITLE
[ToggleButton] no focus outline on Firefox & Safari latest

### ISSUE THREAD

**Issue by mahmoud-zakria-sociomantic** [sociomantic-tsunami/nessie-ui#683]
# Problem

Focusing/clicking on `<ToggleButton>` doesn't make the focus state outline only on FF & Safari.

# Wanted

Fix the focus state outline.

**Comment by mahmoud-zakria-sociomantic** [comment]
I believe that `:active` must be included and leave `:focus` only for Keyboard tabbing navigation.

**Comment by conor-cafferkey-sociomantic** [comment]
Seems like this is the expected behavior in Safari and FF/Mac, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus
