### ISSUE TITLE
[Flounder] Navigation fail on Firefox Linux/Windows

### ISSUE THREAD

**Issue by huei-tan-sociomantic** [sociomantic-tsunami/nessie-ui#684]
# Problem
In Firefox Linux/Windows environment, it will auto select the item in sequence if you navigate up/down.

![oct-30-2018 12-06-21](https://user-images.githubusercontent.com/37908294/47714248-a76eb900-dc3c-11e8-9412-f15e672424b8.gif)

# Wanted

Normally, it should behave
![oct-30-2018 12-07-24](https://user-images.githubusercontent.com/37908294/47714256-adfd3080-dc3c-11e8-8ea2-3700ac3a0ea8.gif)

**Comment by conor-cafferkey-sociomantic** [comment]
This seems to be a Flounder issue. Since we’re phasing out Flounder I’m gonna close this as `res-wontfix`. If this is something that _really_ needs to be fixed then an issue should be opened in the [Flounder repo](https://github.com/sociomantic-tsunami/flounder)
