### ISSUE TITLE
[MacOS][Firefox][Flounder] using keyboards 'up/down' show the native <select> menu 

### ISSUE THREAD

**Issue by mahmoud-zakria-sociomantic** [sociomantic-tsunami/nessie-ui#694]
# Problem

<img width="864" alt="screen shot 2018-10-30 at 11 24 28" src="https://user-images.githubusercontent.com/37908294/47711781-68d60000-dc36-11e8-9cba-cdc12bb52224.png">

# Wanted
Hide the native <select> menu and sync the focus state with Flounder

**Comment by mahmoud-zakria-sociomantic** [comment]
[Also Flounder issue with FireFox in the other OSs](https://github.com/sociomantic-tsunami/nessie-ui/issues/684)

**Comment by conor-cafferkey-sociomantic** [comment]
Seems to be a general Flounder issue with FF. Since we’re phasing out Flounder I’ll close this. If it _really_ needs to be fixed an issue should be opened in the [Flounder repo](https://github.com/sociomantic-tsunami/flounder).
