### ISSUE TITLE
Implement stateful components with default behaviors

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie-ui#718]
### Currently

As purely visual, “dumb” components the Nessie components are – quite deliberately – stateless and do not implement default behaviors. Instead, we provide hooks for the host app to provide interaction behaviors in the form of event callback props.

### Problem

This works fine for simple components like TextInput. However requiring the host app to supply all event handling for more complex components like DatePicker, or components that are compositions of other components like ComboBox or DateTimeInput, means that those components are not usable out of the box.

### Wanted

We should keep the existing “dumb” Nessie components and provide and additional set of stateful components that implement default behaviors (for example, clicking on a ComboBox should open the associated dropdown).

Some requirements:
- The existing Nessie components and their API should remain untouched
- ...more requirements here...

**Comment by conor-cafferkey-sociomantic** [comment]
A couple of stateful component examples:
- [ComboBox implementing a simple `<select>`](https://codepen.io/sociomantic/pen/OZmwYW/?editors=0110)
- [Slider implementing range slider](https://codepen.io/sociomantic/pen/odWpZb/)

**Comment by damian-rodriguez-sociomantic** [comment]
we need to create the following stateful components:
- [ ] ComboBox 
   - [ ] Select 
   - [ ] ComboBox
- [ ] DatePicker
- [ ] DateTimeInput
- [ ] DragNDrop ?
- [ ] IconWithTooltip
- [ ] ListBox ?
- [ ] ModalDialog
- [ ] Module
- [ ] NavItem
- [ ] Paginator ?
- [ ] PasswordInput
- [x] ScrollBox ( already exists )
- [ ] Slider
- [ ] Tabs
- [ ] TagInput
   - [ ] Regular TagInput
   - [ ] DropDown TagInput
- [ ] Uploader ?

**Comment by conor-cafferkey-sociomantic** [comment]
I think we can call this “done”
