### ISSUE TITLE
[Slider] Touch events should prevent default

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie-ui#738]
### Currently

On tablet/mobile if you’re zoomed in and try to drag the slider you end up panning/scrolling instead.

### Wanted

- [x] call `preventDefault()` on the `touchdown` event (I guess)
- [x] check that this doesn’t have any unwanted side effects
- [ ] add regression test

**Comment by mahmoud-zakria-sociomantic** [comment]
I'm not sure, but since events became `passive` things change and became different
![image](https://user-images.githubusercontent.com/37908294/51472172-0db93280-1d79-11e9-8308-b66fd2455031.png)

https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#solution-the-passive-option

**Comment by conor-cafferkey-sociomantic** [comment]
> So I guess we need to specify `passive: false`

Yeah I guess so 👍

**Comment by mahmoud-zakria-sociomantic** [comment]
@conor-cafferkey-sociomantic can you please check this commit? ⬆️ 🔼

**Comment by conor-cafferkey-sociomantic** [comment]
Really sucks that Chrome makes us do this 😠 

The workaround with `react-event-listener` looks legit.... but I’d prefer if we could do this without adding an external dependency: Maybe we can manually call `trackRef.addEventListener( 'touchstart' )` in `componentDidMount` instead?
