### ISSUE TITLE
[Module] Create stateful Component with Hooks

### ISSUE THREAD

**Issue by damian-rodriguez-sociomantic** [sociomantic-tsunami/nessie-ui#744]

**Comment by damian-rodriguez-sociomantic** [comment]
caa3c6b62c0e968a6d2a3c9589617f6f3054960c
dfd9a1cabff40c8716dbeaf0680f6732705c4fe4

**Comment by conor-cafferkey-sociomantic** [comment]
Module has been removed in `master-x` and is unlikely to make a return, so closing this...
