### ISSUE TITLE
Convert all components to Hooks

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie-ui#766]
It’s time to hooks-ify all the things:
- [x] ~[withDropdown](https://github.com/sociomantic-tsunami/nessie-ui/issues/896)~ _will be [removed](https://github.com/sociomantic-tsunami/nessie-ui/issues/903)_
- [x] [Button](https://github.com/sociomantic-tsunami/nessie-ui/issues/767)
- [x] [Card](https://github.com/sociomantic-tsunami/nessie-ui/issues/828)
- [x] [Checkbox](https://github.com/sociomantic-tsunami/nessie-ui/issues/768)
- [ ] [ComboBox](https://github.com/sociomantic-tsunami/nessie-ui/issues/750) _PR_
- [x] [CurrencyInput](https://github.com/sociomantic-tsunami/nessie-ui/pull/887)
- [x] [DatePicker](https://github.com/sociomantic-tsunami/nessie-ui/issues/885)
    - [x] [DatePickerHeader](https://github.com/sociomantic-tsunami/nessie-ui/issues/885)
    - [x] [DatePickerItem](https://github.com/sociomantic-tsunami/nessie-ui/issues/885)
    - [x] [TimeInput](https://github.com/sociomantic-tsunami/nessie-ui/issues/885)
- [x] [DateTimeInput](https://github.com/sociomantic-tsunami/nessie-ui/issues/899)
- [x] [Dropdown](https://github.com/sociomantic-tsunami/nessie-ui/issues/769)
- [x] [Grid](https://github.com/sociomantic-tsunami/nessie-ui/issues/773)
- [x] [GridItem](https://github.com/sociomantic-tsunami/nessie-ui/issues/776)
- [x] [Icon](https://github.com/sociomantic-tsunami/nessie-ui/issues/778)
- [x] [IconButton](https://github.com/sociomantic-tsunami/nessie-ui/issues/780)
- [x] [ListBox](https://github.com/sociomantic-tsunami/nessie-ui/issues/857)
    - [x] ListBoxOption
    - [x] ListBoxOptionGroup
- [x] [Modal](https://github.com/sociomantic-tsunami/nessie-ui/issues/782)
- [x] [PasswordInput](https://github.com/sociomantic-tsunami/nessie-ui/issues/787)
- [x] [ProgressBar](https://github.com/sociomantic-tsunami/nessie-ui/issues/888)
- [x] [ScrollBar](https://github.com/sociomantic-tsunami/nessie-ui/issues/831)
- [x] [ScrollBox](https://github.com/sociomantic-tsunami/nessie-ui/issues/746) 
- [x] [Spinner](https://github.com/sociomantic-tsunami/nessie-ui/issues/838)
- [x] [Tab](https://github.com/sociomantic-tsunami/nessie-ui/issues/840)
- [x] [TabButton](https://github.com/sociomantic-tsunami/nessie-ui/issues/844)
- [x] [Tabs](https://github.com/sociomantic-tsunami/nessie-ui/issues/847)
- [x] [Tag](https://github.com/sociomantic-tsunami/nessie-ui/issues/860)
- [x] [TagInput](https://github.com/sociomantic-tsunami/nessie-ui/issues/867)
- [x] [Text](https://github.com/sociomantic-tsunami/nessie-ui/issues/853)
- [x] [TextArea](https://github.com/sociomantic-tsunami/nessie-ui/pull/884)
- [x] [TextInput](https://github.com/sociomantic-tsunami/nessie-ui/issues/876)
- [x] [TextInputWithIcon](https://github.com/sociomantic-tsunami/nessie-ui/issues/878)
- [x] [Tooltip](https://github.com/sociomantic-tsunami/nessie-ui/issues/894)

For most components, this just means converting (back) to function components and using:
- [`useContext`](https://reactjs.org/docs/hooks-reference.html#usecontext) to consume the theme (all of the above components)
- [`useImperativeHandle`](https://reactjs.org/docs/hooks-reference.html#useimperativehandle)/`forwardRef` to expose a `focus()` function (for components that are focusable; remove any props like `inputRef`, `buttonRef`, etc.)

For stateful components:
- event handler functions should be implemented using [`useCallback`](https://reactjs.org/docs/hooks-reference.html#usecallback)
- derived states calculated in `getDerivedStateFromProps` can be replaced with [`useMemo`](https://reactjs.org/docs/hooks-reference.html#usememo).

**Comment by conor-cafferkey-sociomantic** [comment]
Base branch for this issue: https://github.com/sociomantic-tsunami/nessie-ui/tree/Milestone-Hooks%21

**Comment by conor-cafferkey-sociomantic** [comment]
Hey @daniel-martic-sociomantic, @mahmoud-zakria-sociomantic: I think we should use a custom hook for consuming the theme. 

I’m thinking something like this, it would be used in place of `useContext :

```useTheme.js
import ThemeProvider from '.....'

function useTheme( props )
{
    const { displayName } = useTheme.caller; // `caller` is “nonstandard” JS... should we use it? 😈
    const { [ displayName ] : theme } = useContext( ThemeProvider ); // check out ma fancy destructuring!

    return props.cssMap || // cssMap prop overrides the theme, if defined
        ( typeof theme === 'function' ?  theme( props ) : theme ); // if theme is a function, call it with the current props
}
```

What do you think?

**Comment by conor-cafferkey-sociomantic** [comment]
Right now we have two big-ish problems:
- Enzyme’s shallow render [doesn’t support hooks yet](https://github.com/airbnb/enzyme/issues/1938), so all our shallow tests will fail... not a whole lot we can do about this except wait for Enzyme to support Hooks 😕 
- Our test driver suite for Enzyme full-DOM rendering is broken. Currently the component drivers assume that all components are classes not functions. This is fixable and I will open an issue.

**Comment by mahmoud-zakria-sociomantic** [comment]
> Hey @daniel-martic-sociomantic, @mahmoud-zakria-sociomantic: I think we should use a custom hook for consuming the theme.
> 
> I’m thinking something like this, it would be used in place of `useContext` :
> 
> ```js
> import ThemeProvider from '.....'
> 
> function useTheme( props )
> {
>     const { displayName } = useTheme.caller; // `caller` is “nonstandard” JS... should we use it? 😈
>     const { [ displayName ] : theme } = useContext( ThemeProvider ); // check out ma fancy destructuring!
> 
>     return props.cssMap || // cssMap prop overrides the theme, if defined
>         ( typeof theme === 'function' ?  theme( props ) : theme ); // if theme is a function, call it with the current props
> }
> ```
> 
> What do you think?

@conor-cafferkey-sociomantic Why we would do it? what the problem with `useContext`?

**Comment by conor-cafferkey-sociomantic** [comment]
> what the problem with `useContext`?

Absolutely no problem with `useContext` (this custom hook uses it!)

The problem is having to write something like this in every component is error-prone:
```
import { Theme context } from '....';
I { createCssMap } from '....';
....
const context = useContext( ThemeContext );
const {
    ....,
    cssMap = createCssMap( context.Button, props),
    ....,
} = this.props;
....
```

In particular, the part where we have to specify the component name (here,  `Button`).

**Comment by conor-cafferkey-sociomantic** [comment]
And while we’re at it, we can do something similar when we generate a component `id`:
```
import { generateId } from '....';

function useId( props )
{
    const { displayName } = useTheme.caller; // 😈
    const id = useMemo(
        () => props.id || generateId( displayName  ),
        [ props.id ], // only update the return value if `props.id` changes
    ) ;
    return id;
}
