### ISSUE TITLE
[DateTimeInput] Editing main input broken

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie-ui#803]
### Problem

If you edit the main input the DateTimeInput breaks.

### Wanted

Make editing the main input work.

**Comment by conor-cafferkey-sociomantic** [comment]
Can no longer reproduce 😕 maybe I was doing something weird 😄

**Comment by conor-cafferkey-sociomantic** [comment]
To reproduce:
- open the calendar and pick a date
- in the main input field, delete _both_ minute digits
- kaboom!

**Comment by mahmoud-zakria-sociomantic** [comment]
Related issue https://github.com/sociomantic-tsunami/nessie-ui/issues/826
