### ISSUE TITLE
[DateTimeInput] Cannot clear value

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie-ui#826]
## Problem

Once a `value` (Unix timestamp) has been set, it is not possible to clear it.
### To reproduce:
- set the `value` prop to a Unix timestamp
- set the `value` prop to `undefined` or `null`
### Result:
- previous value persists
### Expected
- value should be cleared

### Wanted
Implement a way to clear the currently-selected value/timestamp. This will probably need to be by explicitly passing `null`, rather than `undefined` (since `undefined` currently makes the component uncontrolled).

**Comment by mahmoud-zakria-sociomantic** [comment]
Related issue https://github.com/sociomantic-tsunami/nessie-ui/issues/803
