### ISSUE TITLE
[Icon] xlinkHref reference to feather-icons needs to be fixed 

### ISSUE THREAD

**Issue by mahmoud-zakria-sociomantic** [sociomantic-tsunami/nessie-ui#870]
# Problem
The names of feather-icons starts with `nessie in `SpriteMap` and in `<Icon>` implementation starts with `icon__[iconName]`.

![image](https://user-images.githubusercontent.com/37908294/52722445-e76b6900-2fab-11e9-96a8-54c8b45f645d.png)

# Wanted
either to get it back to `icon__` or replace xlinkHref with `nessie-`.

**Comment by conor-cafferkey-sociomantic** [comment]
This is fine in `master-x`. Problem is in `Milestone-Hooks!`
